name: Example workflow for Snyk Infrastructure as Code

on: 
  push:
  workflow_dispatch:
  
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check Kubernetes manifest file for issues
        uses: snyk/snyk:alpine
      - name: Running Snyk IaC Test
        run: snyk iac test --report
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}